name = "plant-care-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "plant-care"
database_id = "fcc66b86-ae3d-42c5-be08-8524119197de"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "plant-photos"
